
volumes:
  shared-dir:
    # Define the volume here
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./webNext

services:
  nextjs_app:
    # restart: always
    # command: tail -f /dev/null  
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - shared-dir:/app
      - /app/node_modules
    ports:
      - 3000:3000

  go_app:
    build:
      context: .
      dockerfile: Dockerfile.go_app
    ports:
      - "4696:4696"
    volumes:
      - shared-dir:/go/src/app


# services:
#   magical-first-website-nexxt:
#     # command: tail -f /dev/null  
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./webNext:/app/webNext