FROM golang:latest AS golangBuild
# Set the current working directory inside the container
WORKDIR /app
# Copy the Go module files
COPY magic-first-website-next/go.mod go.mod
# 3333
EXPOSE 4696
# Download and install Go dependencies
# VOLUME /home/monish/code/react/magic-first-website-next
# RUN go mod download
# Copy the rest of the application source code
COPY magic-first-website-next/a.go a.go
# Build the Go app
RUN go build -o goserver .
# Expose port
CMD [ "./goserver" ]