services:
  nextjs_app:
    # restart: always
    # command: tail -f /dev/null  
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./magic-first-website-next:/app
      - /app/node_modules
    ports:
      - 3000:3000

  go_app:
    build:
      context: .
      dockerfile: Dockerfile.go_app
    ports:
      - "4696:4696"
    volumes:
      - ./magic-first-website-next:/go/src/app


# services:
#   magical-first-website-nexxt:
#     # command: tail -f /dev/null  
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./magic-first-website-next:/app/magic-first-website-next